### ISSUE TITLE
'module' object has no attribute 'vectorized'

### ISSUE THREAD

**Issue by altosz** [mrocklin/dask-geopandas#1]
I have dask_geopandas installed from git:
`sudo pip install git+git://git@github.com/mrocklin/dask-geopandas.git`

The versions of dask and pandas are the following:
```dask (0.15.4)
geopandas (0.3.0)
pandas (0.20.3)
```

The code is (taken from [link:](https://nbviewer.jupyter.org/urls/gist.githubusercontent.com/mrocklin/ba6d3e2376e478c344af7e874e6fcbb1/raw/e0db89644f78f4371ee30fbdd517ce9bd6032a5e/nyc-taxi-geospatial.ipynb)
```python
import dask.dataframe as dd
import dask_geopandas as dg
columns = ['pickup_latitude', 'pickup_longitude', 'passenger_count', 
           'fare_amount', 'tip_amount', 'payment_type']
df = dd.read_csv('NY-taxi.csv', usecols=columns)

gf = df.set_geometry(df[['pickup_longitude', 'pickup_latitude']],
                     crs={'init' :'epsg:4326'})
```

I get the following error:

```python
ValueError                                Traceback (most recent call last)
<ipython-input-4-dc2404c15ad2> in <module>()
      1 
      2 gf = df.set_geometry(df[['pickup_longitude', 'pickup_latitude']],
----> 3                      crs={'init' :'epsg:4326'})
      4 gf
      5 # gf2 = dg.sjoin(gf, zones[['zone', 'borough', 'geometry']])

/usr/local/lib/python2.7/site-packages/dask_geopandas/core.pyc in set_geometry(df, geometry, crs)
    439     if isinstance(geometry, dd.DataFrame) and len(geometry.columns) == 2:
    440         a, b = geometry.columns
--> 441         geometry = points_from_xy(geometry[a], geometry[b], crs=crs)
    442 
    443     assert df.npartitions == geometry.npartitions

/usr/local/lib/python2.7/site-packages/dask_geopandas/core.pyc in points_from_xy(x, y, crs)
    431 
    432 def points_from_xy(x, y, crs=None):
--> 433     s = dd.map_partitions(_points_from_xy, x, y, crs=crs)
    434     example = gpd.GeoSeries(Point(0, 0))
    435     return GeoSeries(s.dask, s._name, example, [all_space] * s.npartitions)

/usr/local/lib/python2.7/site-packages/dask/dataframe/core.pyc in map_partitions(func, *args, **kwargs)
   3163 
   3164     if meta is no_default:
-> 3165         meta = _emulate(func, *args, **kwargs)
   3166 
   3167     if all(isinstance(arg, Scalar) for arg in args):

/usr/local/lib/python2.7/site-packages/dask/dataframe/core.pyc in _emulate(func, *args, **kwargs)
   3129     """
   3130     with raise_on_meta_error(funcname(func)):
-> 3131         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   3132 
   3133 

/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.pyc in __exit__(self, type, value, traceback)
     33                 value = type()
     34             try:
---> 35                 self.gen.throw(type, value, traceback)
     36                 raise RuntimeError("generator didn't stop after throw()")
     37             except StopIteration, exc:

/usr/local/lib/python2.7/site-packages/dask/dataframe/utils.pyc in raise_on_meta_error(funcname)
    148                ).format(" in `{0}`".format(funcname) if funcname else "",
    149                         repr(e), tb)
--> 150         raise ValueError(msg)
    151 
    152 

ValueError: Metadata inference failed in `_points_from_xy`.

Original error is below:
------------------------
AttributeError("'module' object has no attribute 'vectorized'",)

Traceback:
---------
  File "/usr/local/lib/python2.7/site-packages/dask/dataframe/utils.py", line 137, in raise_on_meta_error
    yield
  File "/usr/local/lib/python2.7/site-packages/dask/dataframe/core.py", line 3131, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/usr/local/lib/python2.7/site-packages/dask_geopandas/core.py", line 428, in _points_from_xy
    points = gpd.vectorized.points_from_xy(x.values, y.values)
```

**Comment by mrocklin** [comment]
Yes, dask-geopandas currently depends on the [`geopandas-cython`](https://github.com/geopandas/geopandas/tree/geopandas-cython) branch of geopandas

**Comment by altosz** [comment]
Excuse me for the next question, but how can I install it? I do not use conda (if it matters). Thanks in advance

**Comment by mrocklin** [comment]
If you are familiar with git then the following would work

```
git clone git@github.com:geopandas/geopandas.git
cd geopandas
git checkout geopandas-cython
make install
```

There is also conversation on this github issue: https://github.com/geopandas/geopandas/issues/473 

This may have other mechanisms that only use `pip`

**Comment by altosz** [comment]
@mrocklin thank you.
I've installed geos, Cython, followed your instructions.
But executing the code above I get segmentation fault in ipython.

Executing it in plain python, I get the following error:
```sh
Assertion failed: (0 != cs), function GEOSCoordSeq_setOrdinate_r, file geos_ts_c.cpp, line 3851.
```

**Comment by themmes** [comment]
@altosz Did you manage to get this working? After installing dependency `libgeos-dev` I still get the same error in my notebook.

**Comment by mrocklin** [comment]
I've added a note to the README about the current status of this project: https://github.com/mrocklin/dask-geopandas#status

**Comment by jorisvandenbossche** [comment]
@altosz @themmes if you keep running into those compilation errors, it would certainly be useful to open an issue about that in geopandas repo (https://github.com/geopandas/geopandas), as it is something we have to solve.

Further, for just trying out this new version, you can also install (a relatively latest, with some delay) verison via conda-forge:

```
conda install --channel conda-forge/label/dev geopandas
```
