### ISSUE TITLE
module 'geopandas' has no attribute 'points_from_xy'

### ISSUE THREAD

**Issue by khyll** [mrocklin/dask-geopandas#6]
I'm running geopandas on Spyder via Anaconda, and get the following error when attempting to use points_from_xy:

> runfile('C:/Users/kahy/.spyder-py3/karta_spyder3.py', wdir='C:/Users/kahy/.spyder-py3')
> 0.4.1
> Traceback (most recent call last):
> 
>   File "<ipython-input-20-c81ab92f6f27>", line 1, in <module>
>     runfile('C:/Users/kahy/.spyder-py3/karta_spyder3.py', wdir='C:/Users/kahy/.spyder-py3')
> 
>   File "C:\Program Files\Miniconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Program Files\Miniconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "C:/Users/kahy/.spyder-py3/karta_spyder3.py", line 91, in <module>
>     main()
> 
>   File "C:/Users/kahy/.spyder-py3/karta_spyder3.py", line 37, in main
>     geometry=gpd.points_from_xy(mpls['EW_WSG84'], mpls['NS_WSG84']))
> 
> **AttributeError: module 'geopandas' has no attribute 'points_from_xy'** 

I checked similar "has no attribute" errors for geopandas [(https://github.com/mrocklin/dask-geopandas/issues/2)](url) but I didn't understand the bit about cython. My Python is 3.7.3 64-bit Windows, Conca 4.7.5, Spyder 3.3.3, Geopandas 0.4.1. 

Code:

```
import pandas as pd
import geopandas as gpd
from pyproj import Proj, transform

    mpls = pd.read_excel(path_mpls, index_col=0, header=0)

    mpls_gdf = gpd.GeoDataFrame(mpls, 
            geometry=gpd.points_from_xy(mpls['EW_WSG84'], mpls['NS_WSG84']))
```

**Comment by mrocklin** [comment]
This project is not actively maintained

**Comment by sephib** [comment]
A work around is to use `map_partitions` similar to [this example](https://towardsdatascience.com/geospatial-operations-at-scale-with-dask-and-geopandas-4d92d00eb7e8)

**Comment by evawateva33** [comment]
can anyone help with this problem without a work around? I have research partners that were able to use points_from_xy() with no problem. yet my computer seems to dislike geopandas and wont install. I need some help, any would be appreciated.
